add pre hooks

diff --git a/hooks/pre-commit-macos b/hooks/pre-commit-macos
--- a/hooks/pre-commit-macos
+++ b/hooks/pre-commit-macos
@@ -1,19 +1,13 @@
 #!/bin/bash
 
-echo "-----------------Running lint check---------------"
-
-./gradlew  ktlintCheck
-
-statusLint=$?
-
-
 echo "-----------------Running unit test---------------"
 
 ./gradlew test
 
 statusTest=$?
 
-echo "-----------------Done with unit test---------------"
-
-[ $statusLint -ne 0 && $statusTest -ne 0 ] && exit 1
-exit 0
+if [[ $statusTest -ne 0 ]]
+then
+  echo "-----------------Run test fail (fix test)---------------"
+  exit 1
+fi
diff --git a/hooks/pre-commit-windows b/hooks/pre-commit-windows
--- a/hooks/pre-commit-windows
+++ b/hooks/pre-commit-windows
@@ -1,11 +1,13 @@
 #!C:/Program\ Files/Git/usr/bin/sh.exe
 
-echo "-----------------Running lint check---------------"
+echo "-----------------Running unit test---------------"
 
-./gradlew  ktlintCheck
+./gradlew.bat test
 
-status=$?
+statusTest=$?
 
-# return 1 exit code if running checks fails
-[ $status -ne 0 ] && exit 1
-exit 0
+if [[ $statusTest -ne 0 ]]
+then
+  echo "-----------------Run test fail (fix test)---------------"
+  exit 1
+fi
